# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb6b0d8dd2b92161999b2d6154cfd4aca31fdd111fb0f909e280340d38e23fac045c61ca0352551556f3d42b54b10ed88c0864af35ddabbfa72d909e014aa1f7

test:
  secret_key_base: 4940b1f8359a942430765129837f411786087847040596ca1aa1a2c8da81f0677de187521f5507fae31439dc66e3895cd941c430b13cd7867140a68ed78f7427

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
